spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    username: hunseong
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
